#ifndef M_DEFINE_VERSION_H
#define M_DEFINE_VERSION_H
#define TEST_VERSION_1 1
#define TEST_VERSION_2 0
#define TEST_VERSION_3 2
#define TEST_VERSION_4 6
#define TEST_P_VERSION_1 1
#define TEST_P_VERSION_2 0
#define TEST_P_VERSION_3 2
#define TEST_P_VERSION_4 6
#define DSP_SOFTWARE_VERSION "1.0.2.6\0"
#define DSP_PRODUCTION_NAME "XYZprint AM³ᴰᴾ\0"
#define DSP_ORIGINAL_FILE_NAME "XYZprint AM³ᴰᴾ.exe\0"
#endif
